framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'  # Utilise le DSN du fichier .env.local
        envelope:
            sender: 'noreply@example.com'  # Expéditeur par défaut
        enabled: true
