framework:
    notifier:
        chatter_transports:
            # Vous pouvez ajouter des transports pour Slack, Telegram, etc. ici si nécessaire
        texter_transports:
            twilio: '%env(TWILIO_DSN)%'
        channel_policy:
            urgent: ['sms', 'email']
            high: ['sms', 'email']
            medium: ['sms', 'email']
            low: ['sms', 'email']
        admin_recipients:
            - { email: 'chaimakhiari25@gmail.com', phone: '+21693030489' }