<?php

namespace ContainerPwntSLV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VYlEv90Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vYlEv90' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vYlEv90'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pdfGenerator' => ['privates', 'App\\Service\\PdfGeneratorService', 'getPdfGeneratorServiceService', true],
            'reservation' => ['privates', '.errored..service_locator.vYlEv90.App\\Entity\\Reservation', NULL, 'Cannot autowire service ".service_locator.vYlEv90": it needs an instance of "App\\Entity\\Reservation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'pdfGenerator' => 'App\\Service\\PdfGeneratorService',
            'reservation' => 'App\\Entity\\Reservation',
        ]);
    }
}
