<?php

namespace Container1VPndsp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Wj5GlgXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Wj5GlgX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Wj5GlgX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'demande' => ['privates', '.errored..service_locator.Wj5GlgX.App\\Entity\\Demande', NULL, 'Cannot autowire service ".service_locator.Wj5GlgX": it needs an instance of "App\\Entity\\Demande" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'demande' => 'App\\Entity\\Demande',
            'entityManager' => '?',
        ]);
    }
}
