<?php

namespace Container1VPndsp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J14DnboService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J14Dnbo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.J14Dnbo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'compagneRepository' => ['privates', 'App\\Repository\\CompagneRepository', 'getCompagneRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'notifier' => ['privates', 'notifier', 'getNotifierService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'compagneRepository' => 'App\\Repository\\CompagneRepository',
            'entityManager' => '?',
            'notifier' => '?',
            'slugger' => '?',
        ]);
    }
}
