<?php

namespace Container1VPndsp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I9Gz0JgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.I9Gz0Jg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.I9Gz0Jg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'recherche' => ['privates', '.errored..service_locator.I9Gz0Jg.App\\Entity\\Recherche', NULL, 'Cannot autowire service ".service_locator.I9Gz0Jg": it needs an instance of "App\\Entity\\Recherche" but this type has been excluded in "config/services.yaml".'],
        ], [
            'recherche' => 'App\\Entity\\Recherche',
        ]);
    }
}
