<?php

namespace Container1VPndsp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HW7bSYjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hW7bSYj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hW7bSYj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'compagneRepository' => ['privates', 'App\\Repository\\CompagneRepository', 'getCompagneRepositoryService', true],
        ], [
            'compagneRepository' => 'App\\Repository\\CompagneRepository',
        ]);
    }
}
