<?php

namespace ContainerRtnO4gz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZxF2gM5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZxF2gM5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZxF2gM5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'demandeRepository' => ['privates', 'App\\Repository\\DemandeRepository', 'getDemandeRepositoryService', true],
            'invitationRepository' => ['privates', 'App\\Repository\\InvitationRepository', 'getInvitationRepositoryService', true],
        ], [
            'demandeRepository' => 'App\\Repository\\DemandeRepository',
            'invitationRepository' => 'App\\Repository\\InvitationRepository',
        ]);
    }
}
