<?php

namespace ContainerRtnO4gz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BFINwihService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bFINwih' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bFINwih'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'profil' => ['privates', '.errored..service_locator.bFINwih.App\\Entity\\Profil', NULL, 'Cannot autowire service ".service_locator.bFINwih": it needs an instance of "App\\Entity\\Profil" but this type has been excluded in "config/services.yaml".'],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'entityManager' => '?',
            'profil' => 'App\\Entity\\Profil',
            'slugger' => '?',
        ]);
    }
}
