<?php

namespace ContainerRtnO4gz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZBoFWFCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zBoFWFC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zBoFWFC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'equipesRepository' => ['privates', 'App\\Repository\\EquipesRepository', 'getEquipesRepositoryService', true],
        ], [
            'equipesRepository' => 'App\\Repository\\EquipesRepository',
        ]);
    }
}
