<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Equipes extends \App\Entity\Equipes implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'emploisEquipe1' => [parent::class, 'emploisEquipe1', null, 16],
        "\0".parent::class."\0".'emploisEquipe2' => [parent::class, 'emploisEquipe2', null, 16],
        "\0".parent::class."\0".'equipe_id' => [parent::class, 'equipe_id', null, 16],
        "\0".parent::class."\0".'joueur1' => [parent::class, 'joueur1', null, 16],
        "\0".parent::class."\0".'joueur2' => [parent::class, 'joueur2', null, 16],
        "\0".parent::class."\0".'nom_equipe' => [parent::class, 'nom_equipe', null, 16],
        'emploisEquipe1' => [parent::class, 'emploisEquipe1', null, 16],
        'emploisEquipe2' => [parent::class, 'emploisEquipe2', null, 16],
        'equipe_id' => [parent::class, 'equipe_id', null, 16],
        'joueur1' => [parent::class, 'joueur1', null, 16],
        'joueur2' => [parent::class, 'joueur2', null, 16],
        'nom_equipe' => [parent::class, 'nom_equipe', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
