<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'age' => [parent::class, 'age', null, 16],
        "\0".parent::class."\0".'cin' => [parent::class, 'cin', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'equipesJoueur1' => [parent::class, 'equipesJoueur1', null, 16],
        "\0".parent::class."\0".'equipesJoueur2' => [parent::class, 'equipesJoueur2', null, 16],
        "\0".parent::class."\0".'etat' => [parent::class, 'etat', null, 16],
        "\0".parent::class."\0".'fonction' => [parent::class, 'fonction', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isVerified' => [parent::class, 'isVerified', null, 16],
        "\0".parent::class."\0".'loginhistorys' => [parent::class, 'loginhistorys', null, 16],
        "\0".parent::class."\0".'mdp' => [parent::class, 'mdp', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'plainPassword' => [parent::class, 'plainPassword', null, 16],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null, 16],
        "\0".parent::class."\0".'profil' => [parent::class, 'profil', null, 16],
        "\0".parent::class."\0".'reset_token' => [parent::class, 'reset_token', null, 16],
        "\0".parent::class."\0".'token_expiration' => [parent::class, 'token_expiration', null, 16],
        'age' => [parent::class, 'age', null, 16],
        'cin' => [parent::class, 'cin', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'equipesJoueur1' => [parent::class, 'equipesJoueur1', null, 16],
        'equipesJoueur2' => [parent::class, 'equipesJoueur2', null, 16],
        'etat' => [parent::class, 'etat', null, 16],
        'fonction' => [parent::class, 'fonction', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isVerified' => [parent::class, 'isVerified', null, 16],
        'loginhistorys' => [parent::class, 'loginhistorys', null, 16],
        'mdp' => [parent::class, 'mdp', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'plainPassword' => [parent::class, 'plainPassword', null, 16],
        'prenom' => [parent::class, 'prenom', null, 16],
        'profil' => [parent::class, 'profil', null, 16],
        'reset_token' => [parent::class, 'reset_token', null, 16],
        'token_expiration' => [parent::class, 'token_expiration', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
