<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evenement extends \App\Entity\Evenement implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'date' => [parent::class, 'date', null, 16],
        "\0".parent::class."\0".'emploidutempss' => [parent::class, 'emploidutempss', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'image_url' => [parent::class, 'image_url', null, 16],
        "\0".parent::class."\0".'likesDislikes' => [parent::class, 'likesDislikes', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'terrain' => [parent::class, 'terrain', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        'date' => [parent::class, 'date', null, 16],
        'emploidutempss' => [parent::class, 'emploidutempss', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'image_url' => [parent::class, 'image_url', null, 16],
        'likesDislikes' => [parent::class, 'likesDislikes', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'terrain' => [parent::class, 'terrain', null, 16],
        'type' => [parent::class, 'type', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
