<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Terrain extends \App\Entity\Terrain implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null, 16],
        "\0".parent::class."\0".'evenements' => [parent::class, 'evenements', null, 16],
        "\0".parent::class."\0".'heure_fermeture' => [parent::class, 'heure_fermeture', null, 16],
        "\0".parent::class."\0".'heure_ouverture' => [parent::class, 'heure_ouverture', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'prix_par_personne' => [parent::class, 'prix_par_personne', null, 16],
        'adresse' => [parent::class, 'adresse', null, 16],
        'evenements' => [parent::class, 'evenements', null, 16],
        'heure_fermeture' => [parent::class, 'heure_fermeture', null, 16],
        'heure_ouverture' => [parent::class, 'heure_ouverture', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'prix_par_personne' => [parent::class, 'prix_par_personne', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
