<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AnnonceMatch extends \App\Entity\AnnonceMatch implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'annonceId' => [parent::class, 'annonceId', null, 16],
        "\0".parent::class."\0".'dateHeure' => [parent::class, 'dateHeure', null, 16],
        "\0".parent::class."\0".'demandes' => [parent::class, 'demandes', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'joueursRecherches' => [parent::class, 'joueursRecherches', null, 16],
        "\0".parent::class."\0".'lieu' => [parent::class, 'lieu', null, 16],
        "\0".parent::class."\0".'niveau' => [parent::class, 'niveau', null, 16],
        "\0".parent::class."\0".'titre' => [parent::class, 'titre', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        'annonceId' => [parent::class, 'annonceId', null, 16],
        'dateHeure' => [parent::class, 'dateHeure', null, 16],
        'demandes' => [parent::class, 'demandes', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'joueursRecherches' => [parent::class, 'joueursRecherches', null, 16],
        'lieu' => [parent::class, 'lieu', null, 16],
        'niveau' => [parent::class, 'niveau', null, 16],
        'titre' => [parent::class, 'titre', null, 16],
        'user' => [parent::class, 'user', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
