<?php

namespace ContainerAc2Pm7X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_92xPn4HService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.92xPn4H' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.92xPn4H'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chartBuilder' => ['privates', 'chartjs.builder', 'getChartjs_BuilderService', true],
            'produitRepository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'chartBuilder' => '?',
            'produitRepository' => 'App\\Repository\\ProduitRepository',
        ]);
    }
}
