<?php

namespace ContainerAc2Pm7X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfil3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.bFINwih.App\Entity\Profil' shared service.
     *
     * @return \App\Entity\Profil
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.bFINwih": it needs an instance of "App\\Entity\\Profil" but this type has been excluded in "config/services.yaml".');
    }
}
