<?php

namespace ContainerSh4KyRV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OHPtpZAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OHPtpZA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OHPtpZA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'terrain' => ['privates', '.errored..service_locator.OHPtpZA.App\\Entity\\Terrain', NULL, 'Cannot autowire service ".service_locator.OHPtpZA": it needs an instance of "App\\Entity\\Terrain" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'terrain' => 'App\\Entity\\Terrain',
        ]);
    }
}
