<?php

namespace ContainerSh4KyRV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Uso9vx9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uso9vx9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uso9vx9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'recherche' => ['privates', '.errored..service_locator.uso9vx9.App\\Entity\\Recherche', NULL, 'Cannot autowire service ".service_locator.uso9vx9": it needs an instance of "App\\Entity\\Recherche" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'recherche' => 'App\\Entity\\Recherche',
        ]);
    }
}
