<?php

namespace ContainerSh4KyRV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnonceMatch2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.oFn1O2w.App\Entity\AnnonceMatch' shared service.
     *
     * @return \App\Entity\AnnonceMatch
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.oFn1O2w": it needs an instance of "App\\Entity\\AnnonceMatch" but this type has been excluded in "config/services.yaml".');
    }
}
