controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: annotation



# config/routes.yaml
app_home:
  path: /home
  controller: App\Controller\HomeController::index

compagne_show:
    path: /compagne/{id}
    controller: App\Controller\CompagneController::show
    requirements:
        id: '\d+'
app_profil_show:
    path: /profil/{id}
    controller: App\Controller\ProfilController::show

#rana//chaima


admin_produit_new:
    path: /admin/produit/new
    controller: App\Controller\ProduitController::newBackOffice
app_panier_index:
    path: /panier
    controller: App\Controller\PanierController::index

app_panier_add:
    path: /panier/add/{id}
    controller: App\Controller\PanierController::add
    requirements:
        id: '\d+'

app_panier_remove:
    path: /panier/remove/{id}
    controller: App\Controller\PanierController::remove
    requirements:
        id: '\d+'
# In your routes.yaml or wherever you define routes
app_checkout:
    path: /checkout
    controller: App\Controller\PanierController::checkout

app_produit_index:
    path: /produit
    controller: App\Controller\ProduitController::index

