<?php

namespace ContainerPUcSnzO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H75DCYTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.h75DCYT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.h75DCYT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'annonceMatch' => ['privates', '.errored..service_locator.h75DCYT.App\\Entity\\AnnonceMatch', NULL, 'Cannot autowire service ".service_locator.h75DCYT": it needs an instance of "App\\Entity\\AnnonceMatch" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'annonceMatch' => 'App\\Entity\\AnnonceMatch',
            'entityManager' => '?',
        ]);
    }
}
