<?php

namespace ContainerAMmEmCx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J2Ar7CyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.j2Ar7Cy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.j2Ar7Cy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'annonceMatchRepository' => ['privates', 'App\\Repository\\AnnonceMatchRepository', 'getAnnonceMatchRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'annonceMatchRepository' => 'App\\Repository\\AnnonceMatchRepository',
            'entityManager' => '?',
        ]);
    }
}
