<?php

namespace ContainerINeEWxB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BlKJXWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Bl_KJXW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Bl_KJXW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'terrain' => ['privates', '.errored..service_locator.Bl_KJXW.App\\Entity\\Terrain', NULL, 'Cannot autowire service ".service_locator.Bl_KJXW": it needs an instance of "App\\Entity\\Terrain" but this type has been excluded in "config/services.yaml".'],
        ], [
            'terrain' => 'App\\Entity\\Terrain',
        ]);
    }
}
