<?php

namespace ContainerINeEWxB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvitation2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.SI5cjqi.App\Entity\Invitation' shared service.
     *
     * @return \App\Entity\Invitation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.SI5cjqi": it needs an instance of "App\\Entity\\Invitation" but this type has been excluded in "config/services.yaml".');
    }
}
