<?php

namespace ContainerXWWYuX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BaQtoH5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BaQtoH5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BaQtoH5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'annonceMatchRepository' => ['privates', 'App\\Repository\\AnnonceMatchRepository', 'getAnnonceMatchRepositoryService', true],
            'demandeRepository' => ['privates', 'App\\Repository\\DemandeRepository', 'getDemandeRepositoryService', true],
        ], [
            'annonceMatchRepository' => 'App\\Repository\\AnnonceMatchRepository',
            'demandeRepository' => 'App\\Repository\\DemandeRepository',
        ]);
    }
}
