<?php

namespace ContainerXWWYuX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSmsSenderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\SmsBundle\Service\SmsSender' shared autowired service.
     *
     * @return \App\SmsBundle\Service\SmsSender
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'SmsBundle'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'SmsSender.php';

        $a = ($container->privates['notifier'] ?? $container->load('getNotifierService'));

        if (isset($container->privates['App\\SmsBundle\\Service\\SmsSender'])) {
            return $container->privates['App\\SmsBundle\\Service\\SmsSender'];
        }

        return $container->privates['App\\SmsBundle\\Service\\SmsSender'] = new \App\SmsBundle\Service\SmsSender($a);
    }
}
