<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAc2Pm7X\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAc2Pm7X/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAc2Pm7X.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAc2Pm7X\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAc2Pm7X\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ac2Pm7X',
    'container.build_id' => '96a281d2',
    'container.build_time' => 1745968280,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAc2Pm7X');
