<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAMmEmCx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAMmEmCx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAMmEmCx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAMmEmCx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAMmEmCx\App_KernelDevDebugContainer([
    'container.build_hash' => 'AMmEmCx',
    'container.build_id' => '5a3e0b13',
    'container.build_time' => 1745330212,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAMmEmCx');
