<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXWWYuX0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXWWYuX0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXWWYuX0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXWWYuX0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXWWYuX0\App_KernelDevDebugContainer([
    'container.build_hash' => 'XWWYuX0',
    'container.build_id' => 'a827b93b',
    'container.build_time' => 1746051825,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXWWYuX0');
