<?php

namespace ContainerGlIR5Z4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M7RoNlYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.M7RoNlY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.M7RoNlY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'annonceRepository' => ['privates', 'App\\Repository\\AnnonceMatchRepository', 'getAnnonceMatchRepositoryService', true],
            'invitationRepository' => ['privates', 'App\\Repository\\InvitationRepository', 'getInvitationRepositoryService', true],
            'rechercheRepository' => ['privates', 'App\\Repository\\RechercheRepository', 'getRechercheRepositoryService', true],
        ], [
            'annonceRepository' => 'App\\Repository\\AnnonceMatchRepository',
            'invitationRepository' => 'App\\Repository\\InvitationRepository',
            'rechercheRepository' => 'App\\Repository\\RechercheRepository',
        ]);
    }
}
