<?php

namespace ContainerGlIR5Z4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Hb6aAHJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hb6aAHJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hb6aAHJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'profil' => ['privates', '.errored..service_locator.hb6aAHJ.App\\Entity\\Profil', NULL, 'Cannot autowire service ".service_locator.hb6aAHJ": it needs an instance of "App\\Entity\\Profil" but this type has been excluded in "config/services.yaml".'],
        ], [
            'profil' => 'App\\Entity\\Profil',
        ]);
    }
}
