<?php

namespace ContainerK10Txfc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_92xPn4HService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.92xPn4H' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.92xPn4H'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chartBuilder' => ['privates', '.errored..service_locator.92xPn4H.Symfony\\UX\\Chartjs\\Builder\\ChartBuilderInterface', NULL, 'Cannot autowire service ".service_locator.92xPn4H": it references interface "Symfony\\UX\\Chartjs\\Builder\\ChartBuilderInterface" but no such service exists. Did you create a class that implements this interface?'],
            'produitRepository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'chartBuilder' => 'Symfony\\UX\\Chartjs\\Builder\\ChartBuilderInterface',
            'produitRepository' => 'App\\Repository\\ProduitRepository',
        ]);
    }
}
