<?php

namespace ContainerK10Txfc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DgQwthService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._DgQwth' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._DgQwth'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'equipesRepository' => ['privates', 'App\\Repository\\EquipesRepository', 'getEquipesRepositoryService', true],
        ], [
            'em' => '?',
            'equipesRepository' => 'App\\Repository\\EquipesRepository',
        ]);
    }
}
