<?php

namespace ContainerK10Txfc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5CHJ4LiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5CHJ4Li' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5CHJ4Li'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chartBuilder' => ['privates', '.errored..service_locator.5CHJ4Li.Symfony\\UX\\Chartjs\\Builder\\ChartBuilderInterface', NULL, 'Cannot autowire service ".service_locator.5CHJ4Li": it references interface "Symfony\\UX\\Chartjs\\Builder\\ChartBuilderInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'chartBuilder' => 'Symfony\\UX\\Chartjs\\Builder\\ChartBuilderInterface',
        ]);
    }
}
