<?php

namespace ContainerK10Txfc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChartBuilderInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5CHJ4Li.Symfony\UX\Chartjs\Builder\ChartBuilderInterface' shared service.
     *
     * @return \Symfony\UX\Chartjs\Builder\ChartBuilderInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.5CHJ4Li": it references interface "Symfony\\UX\\Chartjs\\Builder\\ChartBuilderInterface" but no such service exists. Did you create a class that implements this interface?');
    }
}
