<?php

namespace ContainerK10Txfc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRechercheService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.I9Gz0Jg.App\Entity\Recherche' shared service.
     *
     * @return \App\Entity\Recherche
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.I9Gz0Jg": it needs an instance of "App\\Entity\\Recherche" but this type has been excluded in "config/services.yaml".');
    }
}
