<?php

namespace ContainerK10Txfc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTerrainService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Bl_KJXW.App\Entity\Terrain' shared service.
     *
     * @return \App\Entity\Terrain
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Bl_KJXW": it needs an instance of "App\\Entity\\Terrain" but this type has been excluded in "config/services.yaml".');
    }
}
